### ISSUE TITLE
Precise preview pane.

### ISSUE THREAD

**Issue by deeputhegamer** [xapian/xapian-gsoc-proposal#6]

**Comment by deeputhegamer** [comment]
Open any search result in its native application from the preview pane.

**Comment by ojwb** [comment]
If you want to discuss/propose a project idea, then the mailing list or IRC are really much better place than here.

I'd suggest you need to expand on what platforms and file formats/applications you would aim to support, in what ways this gives an improved user experience over the current situation, and at least an outline of a plan for how you can make this work.

This isn't reporting an issue with the proposal template here, so closing.

**Comment by deeputhegamer** [comment]
ok sir,
i have one more Idea on which i would like to work on
